spring.application.name=email_writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent
gemini.api.key=AIzaSyA48U9n1mO67iROVD8uK4aQl5W12YdNbTs

server.port=${PORT:8080}
